EXP_NAME: TEST1
DATASET: apy

MODEL: RESNET101

MODE: 'trainval_and_test'

START_EPOCH: 1
END_EPOCH: 25

L_RATE: 10e-6
OPTIM: "SGD"
MOMENTUM: 0.9
CONCEPTS: 'concepts'

K: 100
D: 300

TRAIN_BATCH_SIZE: 256
TEST_BATCH_SIZE: 256
