exp_name: traintest_two_layer_

dataset: nus_wide
concepts: vec
freeze: True

sample: 100
start_epoch: 1
end_epoch: 20

l_rate: 5e-5
optim: SGD
momentum: 0.9

k: 20
d: 300

train_batch_size: 512
test_batch_size: 512
