exp_name: traintest_adaptive_twolayer_adaptive_weight_linear_bias_40_threshold_0.5_tanh_focal

dataset: apy
concepts: attr

start_epoch: 1
end_epoch: 15

l_rate: 1e-4
optim: Adam
momentum: 0.9

loss_args:
  alpha: 1
  gamma: 2
  threshold: 0.5

k: 40
d: 300

train_batch_size: 600
test_batch_size: 600
