exp_name: traintest_concepts_attr_x

dataset: apy
concepts: attr
freeze: True

start_epoch: 1
end_epoch: 26

l_rate: 5e-5
optim: SGD
momentum: 0.9

k: 100
d: 64

train_batch_size: 256
test_batch_size: 512
